In [1]:
import numpy as np

In [9]:
vec = np.array([1, 2, 3, 4, 5])
print(vec)
print('-'*15)

print(type(vec))
print('-'*15)

print(vec.ndim) # 축의 개수
print('-'*15)

print(vec.shape) # 크기

[1 2 3 4 5]
---------------
<class 'numpy.ndarray'>
---------------
1
---------------
(5,)


In [10]:
mat = np.array([[10, 20, 30], [60, 70, 80]])
print(mat)
print('-'*15)

print(type(mat))
print('-'*15)

print(mat.ndim) # 축의 개수
print('-'*15)

print(mat.shape) # 크기

[[10 20 30]
 [60 70 80]]
---------------
<class 'numpy.ndarray'>
---------------
2
---------------
(2, 3)


In [11]:
mat = np.zeros((2,3))
print(mat)
print('-'*15)

mat = np.ones((2,3))
print(mat)
print('-'*15)

mat = np.full((2,2), 7)
print(mat)
print('-'*15)

mat = np.eye(3)
print(mat)
print('-'*15)

mat = np.random.random((2,2))
print(mat)

[[0. 0. 0.]
 [0. 0. 0.]]
---------------
[[1. 1. 1.]
 [1. 1. 1.]]
---------------
[[7 7]
 [7 7]]
---------------
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
---------------
[[0.70468419 0.64655987]
 [0.38069922 0.09351036]]


In [13]:
vec = np.arange(10)
print(vec)
print('-'*15)

n = 2
vec = np.arange(1, 10, n)
print(vec)

[0 1 2 3 4 5 6 7 8 9]
---------------
[1 3 5 7 9]


In [14]:
mat = np.array(np.arange(30)).reshape((5,6))
print(mat)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [16]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat)
print('-'*15)

print(mat[0, :])
print('-'*15)

print(mat[:, 1])

[[1 2 3]
 [4 5 6]]
---------------
[1 2 3]
---------------
[2 5]


In [22]:
mat = np.array([[1, 2], [4, 5], [7, 8]])
print(mat)
print('-'*15)

print(mat[1, 0])
print('-'*15)

print(mat[[2, 1], [0,1]]) # [2,0], [1,1]
print(mat[2, 0])
print(mat[1, 1])

[[1 2]
 [4 5]
 [7 8]]
---------------
4
---------------
[7 5]
7
5


In [27]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)
print('-'*15)

print(x - y)
print('-'*15)

print(x * y)
print('-'*15)

print(x / y)

[5 7 9]
---------------
[-3 -3 -3]
---------------
[ 4 10 18]
---------------
[0.25 0.4  0.5 ]
