https://github.com/aymericdamien/TensorFlow-Examples/blob/master/tensorflow_v2/README.md

# 1 - Introduction
## Hello Tensorflow

In [1]:
import tensorflow as tf

In [7]:
hello = tf.constant('Hello, Tensorflow!')
print(hello)
print(hello.numpy())

tf.Tensor(b'Hello, Tensorflow!', shape=(), dtype=string)
b'Hello, Tensorflow!'


## Basic operations

In [ ]:
import tensorflow as tf

In [7]:
a = tf.constant(2)
b = tf.constant(3)
c = tf.constant(5)

add = tf.add(a, b)
sub = tf.subtract(a, b)
mul = tf.multiply(a, b)
div = tf.divide(a, b)

print('add = ', add.numpy())
print('sub = ', sub.numpy())
print('mul = ', mul.numpy())
print('div = ', div.numpy())

add =  5
sub =  -1
mul =  6
div =  0.6666666666666666


In [4]:
mean = tf.reduce_mean([a, b, c])
sum = tf.reduce_sum([a, b, c])

print('mean = ', mean.numpy())
print('sum = ', sum.numpy())

mean =  3
sum =  10


In [5]:
matrix1 = tf.constant([[1., 2.], [3., 4.]])
matrix2 = tf.constant([[5., 6.], [7., 8.]])

product = tf.matmul(matrix1, matrix2)
product

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [6]:
product.numpy()

array([[19., 22.],
       [43., 50.]], dtype=float32)

## Basic Models
- ### Linear Regression(선형 회귀)
    - #### 회귀 분석 : 관찰된 연속형 변수들에 대해 두 변수 사이의 모형을 구한 뒤 적합도를 측정해 내는 분석 방법
    - #### 선형 회귀 : $y = Wx + b$
        #### 종속 변수 y와 한 개 이상의 독립 변수(또는 설명 변수) X와의 선형 상관 관계를 모델링하는 회귀분석 기법
    

In [8]:
import tensorflow as tf
import numpy as np
rng = np.random

In [9]:
# Parameters
learning_rate = 0.01
training_steps = 1000
display_step = 50

In [10]:
# Training Data
X = np.array([3.3,4.4,5.5,6.71,6.93,4.168,9.779,6.182,7.59,2.167,
              7.042,10.791,5.313,7.997,5.654,9.27,3.1])
Y = np.array([1.7,2.76,2.09,3.19,1.694,1.573,3.366,2.596,2.53,1.221,
              2.827,3.465,1.65,2.904,2.42,2.94,1.3])

#### Weight(가중치) : 독립 변수와 곱해지는 값(직선의 기울기)
#### Bias(편향) : 별도로 더해지는 값(절편)
#### Mean squared error(평균 제곱 오차) : $(정답 - 예측)^2\over{n}$ 으로 정답에 가까울수록 값이 작아지고 오답에 가까울수록 큰 값이 나온다.
#### Stochastic gradient descent(확률적 경사 하강법) : 

In [11]:
# Weight and Bias(가중치와 편향)
W = tf.Variable(rng.randn(), name='weight')
b = tf.Variable(rng.randn(), name='bias')

def linear_regression(x):
    return W * x + b

# Mean squared error(평균 제곱 오차)
def mean_square(y_pred, y_true):
    return tf.reduce_mean(tf.square(y_pred - y_true))

# Stochastic gradient descent(확률적 경사 하강법)
optimizer = tf.optimizers.SGD(learning_rate)