# 계단 오르기
동전을 던져서 앞면(1)이 나오면 한칸을 올라가고  
뒷면(0)이 나오면 한칸을 내려간다.  
동전을 500번 던졌을 때 최종 위치를 구하고,  
10번째 계단에 최초로 도착했을때의 동전 던진 횟수를 구해라. (도착 못 했다면 0 출력)

In [14]:
import numpy as np

In [15]:
rng = np.random.default_rng(seed=12345)
head_tail_arr = rng.integers(0, 2, 500)
# print(head_tail_arr)

In [16]:
up_down_arr = np.where(head_tail_arr, 1, -1)
# print(up_down_arr)

In [17]:
current_stair_arr = up_down_arr.cumsum()
# print(current_stair_arr)

In [29]:
print(f'최종 위치    : {current_stair_arr[-1]}')
print(f'최초 10 도착 : {(current_stair_arr == 10).argmax()}')

최종 위치    : -10
최초 10 도착 : 0


## 100명이 동시에 할 때,  
## 10 위치에 도착했던 인원 수와 10 위치에 도착한 사람들의 최종 위치를 출력해라.

In [35]:
import numpy as np
rng = np.random.default_rng(seed = 12345)
head_tail_arr = rng.integers(0, 2, (100, 500))
print(head_tail_arr)

[[1 0 1 ... 0 1 1]
 [1 0 0 ... 0 1 1]
 [1 1 1 ... 0 1 1]
 ...
 [1 0 0 ... 0 1 0]
 [0 1 1 ... 1 1 1]
 [1 1 1 ... 0 0 1]]


In [36]:
up_down_arr = np.where(head_tail_arr == 1, 1, -1)
print(up_down_arr)

[[ 1 -1  1 ... -1  1  1]
 [ 1 -1 -1 ... -1  1  1]
 [ 1  1  1 ... -1  1  1]
 ...
 [ 1 -1 -1 ... -1  1 -1]
 [-1  1  1 ...  1  1  1]
 [ 1  1  1 ... -1 -1  1]]


In [41]:
current_stair_arr = up_down_arr.cumsum(1)
print(current_stair_arr)

[[  1   0   1 ... -12 -11 -10]
 [  1   0  -1 ... -38 -37 -36]
 [  1   2   3 ...   6   7   8]
 ...
 [  1   0  -1 ...  22  23  22]
 [ -1   0   1 ... -22 -21 -20]
 [  1   2   3 ... -14 -15 -14]]


In [45]:
for i in range(100) :
    print(f'{i + 1} 번째 사람')
    print(f'최종 위치    : {current_stair_arr[i][-1]}')
    print(f'최초 10 도착 : {(current_stair_arr[i] == 10).argmax()}')
    print()

1 번째 사람
최종 위치    : -10
최초 10 도착 : 0

2 번째 사람
최종 위치    : -36
최초 10 도착 : 0

3 번째 사람
최종 위치    : 8
최초 10 도착 : 17

4 번째 사람
최종 위치    : 14
최초 10 도착 : 225

5 번째 사람
최종 위치    : -50
최초 10 도착 : 0

6 번째 사람
최종 위치    : 2
최초 10 도착 : 0

7 번째 사람
최종 위치    : 32
최초 10 도착 : 111

8 번째 사람
최종 위치    : 16
최초 10 도착 : 65

9 번째 사람
최종 위치    : 8
최초 10 도착 : 0

10 번째 사람
최종 위치    : -24
최초 10 도착 : 0

11 번째 사람
최종 위치    : 0
최초 10 도착 : 89

12 번째 사람
최종 위치    : -14
최초 10 도착 : 0

13 번째 사람
최종 위치    : -16
최초 10 도착 : 0

14 번째 사람
최종 위치    : -6
최초 10 도착 : 0

15 번째 사람
최종 위치    : 4
최초 10 도착 : 177

16 번째 사람
최종 위치    : 20
최초 10 도착 : 55

17 번째 사람
최종 위치    : -12
최초 10 도착 : 113

18 번째 사람
최종 위치    : -24
최초 10 도착 : 0

19 번째 사람
최종 위치    : 34
최초 10 도착 : 145

20 번째 사람
최종 위치    : -26
최초 10 도착 : 0

21 번째 사람
최종 위치    : -56
최초 10 도착 : 0

22 번째 사람
최종 위치    : -22
최초 10 도착 : 55

23 번째 사람
최종 위치    : 26
최초 10 도착 : 455

24 번째 사람
최종 위치    : 28
최초 10 도착 : 51

25 번째 사람
최종 위치    : 22
최초 10 도착 : 241

26 번째 사람
최종 위치    : 4
최초 10 도착 : 461

27 번째 사람
최종 위치    : 

In [58]:
pass_10_person_arr = (current_stair_arr == 10).any(axis=1)

print(f'10 도착 인원 : {pass_10_person_arr.sum()} 명')

# final_stair_arr =  []
# for i in range(pass_10_person_arr.size) :
#     if pass_10_person_arr[i] :
#         final_stair_arr.append(current_stair_arr[i][-1])
# print(final_stair_arr)

# 리스트 컴프리헨션을 이용한 방법
final_stair_arr = [current_stair_arr[i][-1] for i in range(pass_10_person_arr.size) if pass_10_person_arr[i]]

print(final_stair_arr)

10 도착 인원 : 58 명
[8, 14, 32, 16, 0, 4, 20, -12, 34, -22, 26, 28, 22, 4, 6, 0, -24, 22, 32, 2, -14, 0, 0, -2, -8, 8, 4, -2, 12, 44, -54, -26, 14, 8, -4, 48, 16, 0, 20, 38, 12, 28, -14, 12, 4, 8, -8, 16, -6, 10, 22, 24, -6, 22, 22, 2, 22, -14]
